pipeline {
  agent any

  environment {
    APP_IMAGE = "python-app:ci"
  }

  stages {

    stage('CI - Unit tests') {
      // Usamos tu Dockerfile para que el entorno sea idéntico al de producción
      agent {
        dockerfile {
          filename 'devops/Dockerfile'
          dir '.'
        }
      }
      steps {
        sh '''
          python --version
          pip install --upgrade pip setuptools wheel
          pytest
        '''
      }
    }

    stage('CI - Docker build') {
      steps {
        sh '''
          # Construye la imagen de la app usando el Dockerfile
          docker build -t ${APP_IMAGE} -f devops/Dockerfile .
        '''
      }
    }

    stage('CD - Deploy (docker compose)') {
      when {
        anyOf {
          branch 'develop'
          branch 'master'
        }
      }
      steps {
        sh '''
          docker compose up -d
        '''
      }
    }

    stage('CD - E2E test') {
      when {
        anyOf {
          branch 'develop'
          branch 'master'
        }
      }
      steps {
        sh '''
          echo "Esperando a que la app esté lista..."
          for i in {1..15}; do
            if curl -s http://localhost:5001 > /dev/null; then
              echo "App lista!"
              exit 0
            fi
            echo "Esperando..."
            sleep 2
          done
          echo "La app no respondió"
          exit 1
        '''
      }
    }

  } // fin de stages

  post {
    always {
      sh '''
        docker compose down --volumes || true
      '''
    }
  }

} // fin de pipeline

