pipeline {

  agent any

  environment {
    APP_IMAGE = "python-app:ci"
  }

  stages {

    /* =========================
       CI
       ========================= */

    stage('CI - Unit tests') {
      agent {
        docker {
          image 'python:3.6-slim'
        }
      }
      steps {
        sh '''
          python --version
          pip install -r requirements.txt
          pytest
        '''
      }
    }

    stage('CI - Docker build') {
      steps {
        sh '''
          docker build -t ${APP_IMAGE} -f devops/Dockerfile .
        '''
      }
    }

    /* =========================
       CD (solo ramas principales)
       ========================= */

    stage('CD - Deploy (docker compose)') {
      when {
        anyOf {
          branch 'develop'
          branch 'master'
        }
      }
      steps {
        sh '''
          docker compose up -d
        '''
      }
    }

stage('CD - E2E test') {
  when {
    anyOf {
      branch 'develop'
      branch 'master'
    }
  }
  steps {
    sh '''
      echo "Esperando a que la app esté lista..."
      for i in {1..15}; do
        if curl -s http://localhost:5001 > /dev/null; then
          echo "App lista!"
          exit 0
        fi
        echo "Esperando..."
        sleep 2
      done
      echo "La app no respondió"
      exit 1
    '''
  }
}

  /* =========================
     LIMPIEZA
     ========================= */

  post {
    always {
      sh '''
        docker compose down --volumes || true
      '''
    }
  }
 }
}
