name: CI (Ejercicio 1 - Triggers)

on:
  push:
    branches: ['**']

  pull_request:
    branches: [develop, master]

  workflow_dispatch:
    inputs:
      RUN_CD:
        description: 'Ejecutar CD (solo develop/master)'
        required: false
        default: false
        type: boolean

jobs:
  dummy:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar contexto
        run: |
          echo "Repo:   $GITHUB_REPOSITORY"
          echo "Ref:    $GITHUB_REF"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Event:  $GITHUB_EVENT_NAME"
          echo "RUN_CD: ${{ github.event.inputs.RUN_CD }}"
